### ISSUE TITLE
Feature-Request: Test Local Endpoint

### ISSUE THREAD

**Issue by VfBfoerst** [neary-ai/neary#3]
Hi again :)   

It would be nice if we could have a simple "Check Local LLM/API" Button to test if the local API is reachable. Maybe just check if the response contains a 200 http status code or tell the user if the request timed out, so he/she could determine if there is a connection failure or if the local API doesn't work as expected.   
  
Thanks :)

**Comment by mightworks** [comment]
Hi there,

If the chat model is unreachable you'll get this error when you try to send a message:

![local_error](https://github.com/neary-ai/neary/assets/42520241/3919589c-bafd-42d5-b1bb-8ee8edddf0e3)

If the chat model accepts the request but produces an error it'll be handled differently.

A "Test Connection" button in the settings would be cool but for now this will have to do.

Thanks!

Joe

**Comment by VfBfoerst** [comment]
Ah I see, thank you, that is totally enough for now. However, I will leave the issue open, as it would be a nice feature in the future :}

**Comment by mightworks** [comment]
We'll add the enhancement label for future reference and close the issue for now to keep the queue uncluttered. Thanks again for the feedback.
