### ISSUE TITLE
Bug? Local API Endpoint/Webserver with Error-Code 500 + Feature-Request

### ISSUE THREAD

**Issue by VfBfoerst** [neary-ai/neary#4]
Hi again :)  
 
While trying to use our local LLM, we get an error message 500 if we send a request from the frontend. I set the "Program" to Local AI:  
![grafik](https://github.com/neary-ai/neary/assets/64251549/c815abb2-5ce2-4417-b6e2-414c37c7ce70)
   
I suppose this is because the endpoint does not fully act as the exact OpenAI API endpoints.  
  
In neary, we see this error message:  
  
![grafik](https://github.com/neary-ai/neary/assets/64251549/7f6c66e3-aae0-4b01-bf3a-47af9ecdc019)
  
In text-form:  
```
[{'type': 'int_type', 'loc': ('body', 'max_tokens'), 'msg': 'Input should be a valid integer', 'input': None, 'url': 'https://errors.pydantic.dev/2.1/v/int_type'}] {"error":{"message":"[{'type': 'int_type', 'loc': ('body', 'max_tokens'), 'msg': 'Input should be a valid integer', 'input': None, 'url': 'https://errors.pydantic.dev/2.1/v/int_type'}]","type":"internal_server_error","param":null,"code":null}} 500 {'error': {'message': "[{'type': 'int_type', 'loc': ('body', 'max_tokens'), 'msg': 'Input should be a valid integer', 'input': None, 'url': 'https://errors.pydantic.dev/2.1/v/int_type'}]", 'type': 'internal_server_error', 'param': None, 'code': None}} <CIMultiDictProxy('Date': 'Mon, 14 Aug 2023 12:48:29 GMT', 'Server': 'uvicorn', 'Content-Length': '243', 'Content-Type': 'application/json')>
```
  
We used the [python-bindings from llama.cpp](https://github.com/abetlen/llama-cpp-python) to provide an api server. I guess it is to much out of scope for this project to support all available APIs and this is totally okay! As the python-bindings are linked in the [llama.cpp project](https://github.com/ggerganov/llama.cpp) it might be worth a look though. If not - I would totally understand that. I will look into the go bindings as well.  
  
As promised in the issue title: an error message providing that there are problems with the API responses/syntax would be nice. This would make the troubleshooting easier.   
  
Thank you! :}

**Comment by mightworks** [comment]
It looks like the llama-cpp-python didn't like the max_tokens implementation. Just pushed a fix and it works! Let me know if you run into any other issues.

![localllama](https://github.com/neary-ai/neary/assets/42520241/1e8a0712-4f28-40f9-8a2f-3461ff9a379e)

**Comment by VfBfoerst** [comment]
@mightworks Good work, works like a charm! ✅  
Thanks! :}
