### ISSUE TITLE
Bug: 401 Unauthorized 

### ISSUE THREAD

**Issue by VfBfoerst** [neary-ai/neary#5]
Hello :)  
  
Regarding to Issue #2 , I cannot authorize after account-creation with authorization enabled.  
When I try to login, I get the following message:  
  
`GET /api/initialize HTTP/1.1" 401 Unauthorize`  
  
Thanks for helpin :}

**Comment by VfBfoerst** [comment]
The message is different from entering the false credentials/password. If I enter an incorrect password, the logs show:  
  
`INFO:     123.123.123.123:62488 - "POST /auth/token HTTP/1.1" 400 Bad Request`

**Comment by mightworks** [comment]
So after you enter your login info you're not redirected anywhere, you stay on the login screen and see the 401 in the console? And no error message under the login form?

If so, it seems like a cookie issue. A couple of other questions:

Are you using docker?

If so, any changes to the docker-compose configuration or the URLs in the .env file?

When you registered initially, were you taken to the app or have you been completely unable to access it without having authentication disabled?

Would you mind quickly testing in another browser?

**Comment by mightworks** [comment]
I'm not certain this was the issue in this case, but cookie settings were updated in this commit: https://github.com/neary-ai/neary/commit/d4c26c2cdf48778689ea83caa38ee6ed40aa6157

SameSite is set to strict which prevent browsers from complaining, and the secure setting is dynamic based on the request url.
